In [70]:
import numpy as np


In [69]:
myList = [1,2,3]


In [7]:
type(myList)

list

In [9]:
myArray = np.array(myList)

In [10]:
myArray


array([1, 2, 3])

In [12]:
type(myArray)

numpy.ndarray

In [14]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [18]:
np.zeros(shape = (5,5))
#burada zeros ,ile elmanları 0 yapmak istedik ve 5,5 bir toblo oluşturmsaını
#istedim

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.zeros(shape=(10,10))
#degerler 0 aldı çünkü zeros ile aldık

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
type(0)

int

In [21]:
np.ones(shape=(1,3))

array([[1., 1., 1.]])

In [23]:
np.ones((3,3)) #aynı şeyler bunmlar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
 random = np.random.randint(0,100,10)

In [30]:
random

array([ 0,  9, 23,  5, 70, 11, 11, 15, 55, 25])

random


In [35]:
 random3 = np.random.randint(0,100,10) # arr kendi oluşturdu

In [39]:
random3

array([53,  7, 49, 76, 21, 50, 16, 87, 44, 55])

In [40]:
random3.max()

87

In [41]:
random.min()

0

In [42]:
random.argmin() #burda en küçük nindixi verdi bize

0

In [43]:
random.mean() # burada oratalma bulundu

22.4

In [45]:
random.shape # burada lengt bulduk

(10,)

In [46]:
random.reshape((2,5))

array([[ 0,  9, 23,  5, 70],
       [11, 11, 15, 55, 25]])

In [52]:
mat = np.arange(0,100).reshape(10,10)

In [54]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [55]:
mat[5,2]

52

In [57]:
mat[0,9]

9

In [59]:
mat[0,]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
mat[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [63]:
mat[:,1].reshape(1,10)

array([[ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]])

In [65]:
mat[:,1].reshape(10,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [66]:
mat


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
mat[0:2,0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])